# version: '3.8'
# services:
#   backend:
#     build:
#       context: ./backend
#     command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8001
#     volumes:
#       - ./backend:/app
#     expose:
#       - 8001

#   frontend:
#     build:
#       context: ./frontend
#     volumes:
#       - ./frontend:/app
#     expose:
#       - 8082

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - /etc/letsencrypt:/etc/letsencrypt:ro
#     depends_on:
#       - backend
#       - frontend
