name: Deploy Angular Application

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.17.1
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build -- --prod

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile  # Adjust this if your Dockerfile is located elsewhere
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/calkulator_frontend:latest

    - name: Deploy to OVH VPS
      run: |
        ssh -o StrictHostKeyChecking=no username@${{ secrets.OVH_VPS_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/calkulator_frontend:latest
        docker stop calkulator_frontend || true
        docker rm calkulator_frontend || true
        docker run -d --name calkulator_frontend -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/angular-app:latest
        EOF
