name: Deploy Django Application

on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'


    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./equation_solver/

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile  # Adjust this if your Dockerfile is located elsewhere
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/equation_solver:latest

    - name: Deploy to OVH VPS
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.OVH_VPS_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/equation_solver:latest
        docker stop equation_solver || true
        docker rm equation_solver || true
        docker run -d --name equation_solver -p 8001:8001 ${{ secrets.DOCKER_HUB_USERNAME }}/equation_solver:latest
        EOF
