name: Deploy Django Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to OVH VPS
      run: |
        ssh -o StrictHostKeyChecking=no username@${{ secrets.OVH_VPS_IP }} << 'EOF'
        cd /path/to/your/django/project
        git pull
        docker-compose down
        docker-compose up --build -d
        EOF
